# Generated by Django 3.1.7 on 2021-03-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=30, verbose_name='Course ID')),
                ('name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('section', models.CharField(blank='True', default='N/A', max_length=30, verbose_name='Section/Group')),
            ],
            options={
                'unique_together': {('id', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('startingTime', models.TimeField(verbose_name='Starts')),
                ('endingTime', models.TimeField(verbose_name='Ends')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('initial', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('courses', models.ManyToManyField(to='schedule.Course')),
                ('slots', models.ManyToManyField(to='schedule.Slot')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('courses', models.ManyToManyField(to='schedule.Course')),
            ],
        ),
    ]
